name: Django-Postgres-Docker CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs CI/CD when code is pushed to `main`

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d testdb"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install flake8
      
    #   - name: Run linting
    #     run: flake8 .

      - name: Run Migrations
        env:
          DB_NAME: testdb
          DB_USER: testuser
          DB_PASSWORD: testpassword
          DB_HOST: localhost
        run: |
          python manage.py migrate
          
      - name: Run Django tests
        env:
            DB_NAME: test_db
            DB_USER: test_user
            DB_PASSWORD: test_password
            DB_HOST: localhost
        run: python manage.py test

      - name: Deploy (Optional)
        if: success()
        run: |
          echo "Tests passed! Ready for deployment"
